name: CD

on:
  push:
    branches:
      - main  # Trigger the pipeline only on pushes to the main branch

jobs:
  build_and_upload:
    name: Build and Upload Artifact to S3
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.build_and_package.outputs.artifact_name }}  # Pass artifact name to the next job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install Dependencies
        run: npm install

      - name: Build and Package Artifact
        id: build_and_package  # Give this step an ID so that we can reference its output
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)
          zip -r app-${VERSION}.zip .
          echo "Artifact created: app-${VERSION}.zip"
          echo "artifact_name=app-${VERSION}.zip" >> $GITHUB_ENV  # Use $GITHUB_ENV to store the artifact name

      - name: Upload Artifact to S3
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)
          aws s3 cp app-${VERSION}.zip s3://dreamteam-bucket/app-${VERSION}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build_and_upload  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy to EC2 via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name dreamteam-deploy \
            --deployment-group-name production-group \
            --s3-location bucket=dreamteam-bucket,key=s3://dreamteam-bucket/${{ needs.build_and_upload.outputs.artifact_name }},bundleType=zip
